#include "src_defines.h"


const char *verbum_file_h_contents = "typedef struct VerbumContext {\n"
"	struct {\n"
"		void *(*new)(size_t n);\n"
"		void (*delete)(void *ptr);\n"
"		void *(*resize)(void *ptr, size_t size);\n"
"		void *(*copy)(void *data, size_t size);\n"
"	} memory;\n"
"	struct {\n"
"		//void *stream;\n"
"		const char *(*source)(void *stream);\n"
"		uint32_t (*get)(void *stream);\n"
"		uint32_t (*unget)(void *stream);\n"
"		uint32_t (*tell)(void *stream);\n"
"		bool (*at_end)(void *stream);\n"
"		void *(*open)(const char *path);\n"
"		void (*close)(void *stream);\n"
"		char *(*copy_from)(void *stream, size_t offset, size_t nbytes);\n"
"	} io;\n"
"} VerbumContext;\n";

const char *verbum_parser_file_h_contents =
"#ifndef VERBUM_PARSER_H\n"
"#define VERBUM_PARSER_H\n"
"\n"
"#include <stdlib.h>\n"
"#include <stdbool.h>\n"
"\n"
"#include \"cvector.h\"\n"
"\n"
"#include \"verbum_ast.h\"\n"
"#include \"verbum_lexer.h\"\n"
"#include \"verbum_token.h\"\n"
"\n"
"/* Opaque declaration */\n"
"typedef struct Parser Parser;\n"
"\n"
"/* Constructs a new Parser\n"
" *\n"
" * PARAMETERS:\n"
" * 	path: path to a file to parse\n"
" *\n"
" * RETURNS:\n"
" * 	Success: a pointer to a Parser\n"
" * 	Failure: NULL\n"
" */\n"
"Parser *parser_new(VerbumContext *ctx, const char *path);\n"
"\n"
"/* Deletes a Parser\n"
" *\n"
" * PARAMETERS:\n"
" * 	p: Parser to delete\n"
" */\n"
"void parser_delete(Parser *p);\n"
"\n"
"/* Executes the parsing process for a Parser\n"
" *\n"
" * PARAMETERS:\n"
" * 	p: Parser to execute\n"
" *\n"
" * RETURNS:\n"
" * 	A pointer to a Unit representing the parsed\n"
" * 	file passed in with the path in parser_new\n"
" */\n"
"AST *parser_parse(Parser *p);\n"
"\n"
"\n"
"/* Parser struct\n"
" *\n"
" * MEMBERS:\n"
" * 	l: file Lexer\n"
" * 	previous: previously processed Token from l\n"
" * 	current: the current token in l\n"
" * 	peek: the peeked token in l\n"
" */\n"
"typedef struct Parser {\n"
"	VerbumContext *ctx;\n"
"	Lexer *l;\n"
"	Token previous;\n"
"	Token current;\n"
"	Token peek;\n"
"	const char *error;\n"
"	cvector(Token) save;\n"
"	size_t savepos;\n"
"	size_t savedepth;\n"
"} Parser;\n"
"\n"
"\n"
"/* Advances the parser\n"
" *\n"
" * PARAMETERS:\n"
" * 	p: parser to advance\n"
" *\n"
" * RETURNS:\n"
" * 	the next token\n"
" */\n"
"Token parser_advance(Parser *p);\n"
"\n"
"/* Retrieves the previous token\n"
" *\n"
" * PARAMETERS:\n"
" * 	p: the parser to get the previous token\n"
" *\n"
" * RETURNS:\n"
" * 	the previous token\n"
" */\n"
"Token parser_previous(Parser *p);\n"
"\n"
"/* Retrieves the current token\n"
" *\n"
" * PARAMETERS:\n"
" * 	p: the parser to get the current token\n"
" *\n"
" * RETURNS:\n"
" * 	the current token\n"
" */\n"
"Token parser_current(Parser *p);\n"
"\n"
"/* Checks if a Parser's previously processed Token is of a certain TokenType\n"
" *\n"
" * PARAMETERS:\n"
" * 	p: Parser to check\n"
" * 	tt: TokenType to check for\n"
" *\n"
" * RETURNS:\n"
" * 	If the previously parsed token is of the given type\n"
" */\n"
"bool parser_previous_is(Parser *p, TokenType tt);\n"
"\n"
"/* Peeks the next token without advancing\n"
" *\n"
" * PARAMETERS:\n"
" * 	p: the parser to get the next token\n"
" *\n"
" * RETURNS:\n"
" *	the peeked token\n"
" */\n"
"Token parser_peek2(Parser *p);\n"
"Token parser_peek(Parser *p, size_t peek);\n"
"\n"
"/* Checks if the next token is of the desired type\n"
" *\n"
" * PARAMETERS:\n"
" * 	p: the parser to check\n"
" * 	tt: the desired token type\n"
" *\n"
" * RETURNS:\n"
" * 	if the next token is of the desired type\n"
" */\n"
"bool parser_check(Parser *p, TokenType tt);\n"
"bool parser_check2(Parser *p, const char *tl);\n"
"\n"
"/* Checks and advances if the next token is of the desired type\n"
" *\n"
" * PARAMETERS:\n"
" * 	p: parser to match to\n"
" * 	tt: desired type\n"
" *\n"
" * RETURNS:\n"
" * 	true: if the match was successful\n"
" * 	false: if the match was unsuccessful\n"
" */\n"
"bool parser_match(Parser *p, TokenType tt);\n"
"bool parser_match2(Parser *p, const char *tl);\n"
"\n"
"/* Checks and advances if the next token is any of the desired types\n"
" *\n"
" * PARAMETERS:\n"
" * 	p: parser to match to\n"
" * 	tts: an array of expected TokenTypes\n"
" * 	n: length of tts\n"
" *\n"
" * RETURNS:\n"
" * 	true: if the match was successful\n"
" * 	false: if the match was unsuccessful\n"
" */\n"
"bool parser_match_any(Parser *p, TokenType *tts, size_t n);\n"
"\n"
"/* Checks if the parser is at the end of the token stream\n"
" *\n"
" * PARAMETERS:\n"
" * 	p: parser to check\n"
" *\n"
" * RETURNS:\n"
" * 	true: if the parser is at the end\n"
" * 	false: if the parser is not at the end\n"
" */\n"
"bool parser_at_end(Parser *p);\n"
"\n"
"const char *parser_set_error(Parser *p, const char *error);\n"
"\n"
"void parser_reset_error(Parser *p);\n"
"\n"
"bool parser_errored(Parser *p);\n"
"\n"
"%s *parser_parse_internal(Parser *p);\n"
"#endif\n";

const char *verbum_parser_file_c_contents = 
"Parser *parser_new(VerbumContext *ctx, const char *path) {\n"
"	Parser *result = ctx->memory.new(1 * sizeof(*result));\n"
"\n"
"	if(result != NULL) {\n"
"		result->ctx = ctx;\n"
"		result->l = lexer_new(ctx, path);\n"
/* "		result->previous = (Token) {\n"
"			.tag = TokenType_Whitespace,\n"
"			.lexeme = NULL,\n"
"		};\n" */
//"		result->current = lexer_get_token(result->l);\n"
//"		result->peek = lexer_get_token(result->l);\n"
"		result->save = NULL;\n"
"		result->savepos = 0;\n"
"		result->savedepth = 0;\n"
"	}\n"
"\n"
"	return result;\n"
"}\n"
"\n"
"static size_t parser_save(Parser *p) {\n"
"	p->savedepth += 1;\n"
"	return p->savepos;\n"
"}\n"
"\n"
"static void parser_rewind(Parser *p, size_t checkpoint) {\n"
"	p->savepos = checkpoint;\n"
"}\n"
"static void parser_commit(Parser *p) {\n"
"	if(p->savedepth > 0) {\n"
"		p->savedepth -= 1;\n"
"	}\n"
"\n"
"	if(p->savedepth == 0) {\n"
"		// Clean\n"
"	}\n"
"}\n"
"\n"
"void parser_delete(Parser *p) {\n"
"	lexer_delete(p->l);\n"
"	p->ctx->memory.delete(p);\n"
"}\n"
"\n"
"AST *parser_parse(Parser *p) {\n"
"	%s *result = parser_parse_internal(p);\n"
"\n"
"	return result;\n"
"}\n"
"\n"
"Token parser_advance2(Parser *p) {\n"
"	if(!parser_at_end(p)) {\n"
"		Token t;\n"
"\n"
"		do {\n"
"			t = lexer_get_token(p->l);\n"
"		} while(t.tag == TokenType_Whitespace);\n"
"\n"
"		p->previous = p->current;\n"
"		p->current = p->peek;\n"
"		p->peek = t;\n"
"		p->error = NULL;\n"
"	}\n"
"\n"
"	return parser_current(p);\n"
"}\n"
"\n"
"Token parser_advance(Parser *p) {\n"
"	if(p->savepos < cvector_size(p->save)) {\n"
"		return p->save[p->savepos++];\n"
"	}\n"
"\n"
"	Token t;\n"
"\n"
"	do {\n"
"		t = lexer_get_token(p->l);\n"
"	} while(t.tag == TokenType_Whitespace);\n"
"\n"
"	if(p->savedepth > 0) {\n"
"		cvector_push_back(p->save, t);\n"
"		p->savepos += 1;\n"
"	} else {\n"
"		cvector_free(p->save);\n"
"		p->save = NULL;\n"
"		cvector_push_back(p->save, t);\n"
"		p->savepos = 1;\n"
"	}\n"
"\n"
"	return t;\n"
"}\n"
"\n"
"bool parser_at_end(Parser *p) {\n"
"	return parser_current(p).tag == TokenType_EOF;\n"
"}\n"
"\n"
"Token parser_previous(Parser *p) {\n"
//"	return p->previous;\n"
"	if(p->savepos == 0) {\n"
"		return (Token) {\n"
"			.tag = TokenType_Whitespace,\n"
"			.lexeme = NULL,\n"
"		};\n"
"	}\n"
"\n"
"	return p->save[p->savepos - 1];\n"
"}\n"
"\n"
"Token parser_current(Parser *p) {\n"
"	return parser_peek(p, 0);\n"
//"	return p->current;\n"
"}\n"
"\n"
"Token parser_peek(Parser *p, size_t peek) {\n"
"	size_t idx = p->savepos + peek;\n"
"\n"
"	while(idx >= cvector_size(p->save)) {\n"
"		Token t = lexer_get_token(p->l);\n"
"\n"
"		if(t.tag != TokenType_Whitespace) {\n"
"			cvector_push_back(p->save, t);\n"
"\n"
"			if(t.tag == TokenType_EOF) {\n"
"				break;\n"
"			}"
"		}\n"
"	}\n"
"\n"
"	if(idx >= cvector_size(p->save)) {\n"
"		return p->save[cvector_size(p->save) - 1];\n"
"	}\n"
"\n"
"	return p->save[idx];\n"
"}\n"
"\n"
"Token parser_peek2(Parser *p) {\n"
"	return p->peek;\n"
"}\n"
"\n"
"bool parser_check(Parser *p, TokenType tt) {\n"
"	return parser_current(p).tag == tt;\n"
"}\n"
"\n"
"bool parser_check2(Parser *p, const char *tl) {\n"
"	return verbum_token_get_lexeme_type(parser_current(p).lexeme) == verbum_token_get_lexeme_type(tl);\n"
"}\n"
"\n"
"bool parser_previous_is(Parser *p, TokenType tt) {\n"
"	return parser_previous(p).tag == tt;\n"
"}\n"
"\n"
"bool parser_match(Parser *p, TokenType tt) {\n"
"	if(parser_check(p, tt)) {\n"
"		parser_advance(p);\n"
"\n"
"		return true;\n"
"	}\n"
"\n"
"	return false;\n"
"}\n"
"\n"
"bool parser_match2(Parser *p, const char *tl) {\n"
"	if(parser_check2(p, tl)) {\n"
"		parser_advance(p);\n"
"\n"
"		return true;\n"
"	}\n"
"\n"
"	return false;\n"
"}\n"
"\n"
"bool parser_match_any(Parser *p, TokenType *tts, size_t n) {\n"
"	for(size_t i = 0; i < n; i++) {\n"
"		if(parser_match(p, tts[i])) {\n"
"			return true;\n"
"		}\n"
"	}\n"
"\n"
"	return false;\n"
"}\n"
"\n"
"const char *parser_set_error(Parser *p, const char *error) {\n"
"	p->error = error;\n"
"\n"
"	return error;\n"
"}\n"
"\n"
"void parser_reset_error(Parser *p) {\n"
"	p->error = NULL;\n"
"}\n"
"\n"
"bool parser_errored(Parser *p) {\n"
"	return p->error != NULL;\n"
"}\n"
"\n"
"%s *parser_parse_internal(Parser *p) {\n"
"	return parser_parse_%s(p);\n"
"}\n";

const char *verbum_lexer_file_h_contents =
"#ifndef VERBUM_LEXER_H\n"
"#define VERBUM_LEXER_H\n"
"\n"
"#include <stdbool.h>\n"
"#include <stdint.h>\n"
"\n"
"#include \"verbum_token.h\"\n" // token
"#include \"verbum.h\"\n"
"\n"
"\n"
"/* Opaque declaration */\n"
"typedef struct Lexer Lexer;\n"
"\n"
"/* Constructs a new Lexer\n"
" *\n"
" * PARAMETERS:\n"
" * 	path: path of file to open\n"
" *\n"
" * RETURNS:\n"
" * 	A pointer to a Lexer or NULL on failure\n"
" */\n"
"Lexer *lexer_new(VerbumContext *ctx, const char *path);\n"
"\n"
"/* Deletes a Lexer\n"
" *\n"
" * PARAMETERS:\n"
" * 	l: a pointer to a lexer\n"
" */\n"
"void lexer_delete(Lexer *l);\n"
"\n"
"/* Retrieves a token\n"
" *\n"
" * PARAMETERS:\n"
" * 	l: a pointer to a Lexer\n"
" *\n"
" * RETURNS:\n"
" * 	The next Token in the stream\n"
" */\n"
"Token lexer_get_token(Lexer *l);\n"
"\n"
"const char *lexer_get_source(Lexer *l);\n"
"\n"
"#endif";

const char *verbum_lexer_file_c_contents =
"#include <stdio.h>\n"
"#include <stdint.h>\n"
"#include <ctype.h>\n"
"\n"
"#include \"verbum_lexer.h\"\n"
"#include \"verbum_token.h\"\n"
"#include \"verbum.h\"\n"
"\n"
"\n"
"/* Advances a Lexer's position\n"
" *\n"
" * PARAMETERS:\n"
" * 	l: pointer to a Lexer to advance\n"
" * \n"
" * RETURNS:\n"
" * 	The retrieved character from the given Lexer's stream\n"
" */\n"
"static uint32_t lexer_advance(Lexer *l);\n"
"\n"
"/* Retrieves the current character of a Lexer\n"
" *\n"
" * PARAMETERS:\n"
" * 	l: a pointer to a Lexer to process\n"
" *\n"
" * RETURNS:\n"
" * 	The current character in the Lexer's stream\n"
" */\n"
"static uint32_t lexer_current_character(Lexer *l);\n"
"\n"
"/* Peeks a character in a Lexer's stream\n"
" *\n"
" * PARAMETERS:\n"
" * 	l: a pointer to a Lexer to process\n"
" *\n"
" * RETURNS:\n"
" * 	The next character in the Lexer's stream\n"
" */\n"
"static uint32_t lexer_peek_character(Lexer *l);\n"
"\n"
"/* Undos the previous action by a Lexer\n"
" *\n"
" * PARAMETERS:\n"
" * 	l: a pointer to a Lexer to process\n"
" */\n"
"static void lexer_undo(Lexer *l);\n"
"\n"
"/* Checks if a Lexer is at the end of its stream\n"
" *\n"
" * PARAMETERS:\n"
" * 	l: a pointer to a Lexer to check\n"
" *\n"
" * RETURNS:\n"
" *	true if the given Lexer is at the end, false otherwise\n"
" */\n"
"static bool lexer_at_end(Lexer *l);\n"
"\n"
"/* Reports an error encountered by the Lexer\n"
" *\n"
" * PARAMETERS:\n"
" * 	l: a pointer to a Lexer to propogate the error from\n"
" * 	c: the character that caused the error\n"
" */\n"
"static void lexer_report_error(Lexer *l, uint32_t c);\n"
"\n"
"/* Retrieves a token\n"
" *\n"
" * PARAMETERS:\n"
" * 	l: a pointer to a Lexer\n"
" *\n"
" * RETURNS:\n"
" * 	The next Token in the stream\n"
" */\n"
"static Token lexer_lex(Lexer *l);\n"
"\n"
"/* Lexer struct\n"
" *\n"
" * MEMBERS:\n"
" * 	f: a pointer to a UTF8File to read from\n"
" * 	pos:\n"
" * 		row: current row in the file\n"
" * 		column: current column in the file\n"
" * 	cc: current character\n"
" */\n"
"typedef struct Lexer {\n"
"	void *stream;\n"
"	const char *path;\n"
"	VerbumContext *ctx;\n"
"	struct {\n"
"		uint32_t row;\n"
"		uint32_t col;\n"
"	} pos;\n"
"	uint32_t cc;\n"
"} Lexer;\n"
"\n"
"Lexer *lexer_new(VerbumContext *ctx, const char *path) {\n"
"	Lexer *result = ctx->memory.new(1 * sizeof(*result));\n"
"\n"
"	if(result != NULL) {\n"
"		result->ctx = ctx;\n"
"		result->stream = result->ctx->io.open(path);\n"
"		result->path = path;\n"
"		result->pos.row = 1;\n"
"		result->pos.col = 1;\n"
"		result->cc = lexer_advance(result);\n"
"\n"
"		if(result->stream == NULL) {\n"
"			result->ctx->memory.delete(result);\n"
"\n"
"			result = NULL;\n"
"		}\n"
"	}\n"
"\n"
"	return result;\n"
"}\n"
"\n"
"void lexer_delete(Lexer *l) {\n"
"	l->ctx->io.close(l->stream);\n"
"	l->ctx->memory.delete(l);\n"
"}\n"
"\n"
"Token lexer_get_token(Lexer *l) {\n"
"	return lexer_lex(l);\n"
"}\n"
"\n"
"const char *lexer_get_source(Lexer *l) {\n"
"\treturn l->ctx->io.source(l->stream);\n"
"}\n"
"\n"
"uint32_t lexer_advance(Lexer *l) {\n"
"	uint32_t result = '\\0';\n"
"\n"
"	if(!lexer_at_end(l)) {\n"
"		result = l->ctx->io.get(l->stream);\n"
"\n"
"		if(result == \'\\n\') {\n"
"			l->pos.row += 1;\n"
"			l->pos.col = 1;\n"
"		} else {\n"
"			l->pos.col += 1;\n"
"		}\n"
"\n"
"		l->cc = result;\n"
"	}\n"
"\n"
"	return result;\n"
"}\n"
"\n"
"uint32_t lexer_current_character(Lexer *l) {\n"
"	return l->cc;\n"
"}\n"
"\n"
"uint32_t lexer_peek_character(Lexer *l) {\n"
"	uint32_t result = l->ctx->io.get(l->stream);\n"
"\n"
"	l->ctx->io.unget(l->stream);\n"
"\n"
"	return result;\n"
"}\n"
"\n"
"void lexer_undo(Lexer *l) {\n"
"	l->ctx->io.unget(l->stream);\n"
"}\n"
"\n"
"bool lexer_at_end(Lexer *l) {\n"
"	return l->ctx->io.at_end(l->stream);\n"
"}\n"
"\n"
"void lexer_report_error(Lexer *l, uint32_t c) {\n"
"	fprintf(stderr, \"%%s: (%%d:%%d) unrecognized token \'%%lc\'\\n\", l->path, l->pos.row, l->pos.col, c);\n"
"}\n";

const char *verbum_token_file_h_contents;

