#include "src_defines.h"


const char *verbum_file_h_contents = "typedef struct VerbumContext {\n"
"	struct {\n"
"		void *(*new)(size_t n);\n"
"		void (*delete)(void *ptr);\n"
"		void *(*resize)(void *ptr, size_t size);\n"
"		void *(*copy)(void *data, size_t size);\n"
"	} memory;\n"
"	struct {\n"
"		void *stream;\n"
"		uint32_t (*get)(void *stream);\n"
"		uint32_t (*unget)(void *stream);\n"
"		uint32_t (*tell)(void *stream);\n"
"		bool (*at_end)(void *stream);\n"
"		void *(*open)(const char *path);\n"
"		void (*close)(void *stream);\n"
"		char *(*copy_from)(void *stream, size_t offset, size_t nbytes);\n"
"	} io;\n"
"} VerbumContext;\n";

const char *verbum_parser_file_h_contents =
"#ifndef VERBUM_PARSER_H\n"
"#define VERBUM_PARSER_H\n"
"#include <stdlib.h>\n"
"#include <stdbool.h>\n"
"#include \"%s\"\n"
"#include \"%s\"\n"
"#include \"%s\"\n"
"/* Opaque declaration */\n"
"typedef struct Parser Parser;\n"
"\n"
"/* Constructs a new Parser\n"
" *\n"
" * PARAMETERS:\n"
" * 	path: path to a file to parse\n"
" *\n"
" * RETURNS:\n"
" * 	Success: a pointer to a Parser\n"
" * 	Failure: NULL\n"
" */\n"
"Parser *parser_new(const char *path);\n"
"\n"
"/* Deletes a Parser\n"
" *\n"
" * PARAMETERS:\n"
" * 	p: Parser to delete\n"
" */\n"
"void parser_delete(Parser *p);\n"
"\n"
"/* Executes the parsing process for a Parser\n"
" *\n"
" * PARAMETERS:\n"
" * 	p: Parser to execute\n"
" *\n"
" * RETURNS:\n"
" * 	A pointer to a Unit representing the parsed\n"
" * 	file passed in with the path in parser_new\n"
" */\n"
"AST *parser_parse(Parser *p);\n"
"\n"
"\n"
"/* Parser struct\n"
" *\n"
" * MEMBERS:\n"
" * 	l: file Lexer\n"
" * 	previous: previously processed Token from l\n"
" * 	current: the current token in l\n"
" * 	peek: the peeked token in l\n"
" */\n"
"typedef struct Parser {\n"
"	Lexer *l;\n"
"	Token previous;\n"
"	Token current;\n"
"	Token peek;\n"
"	const char *error;\n"
"} Parser;\n"
"\n"
"\n"
"/* Advances the parser\n"
" *\n"
" * PARAMETERS:\n"
" * 	p: parser to advance\n"
" *\n"
" * RETURNS:\n"
" * 	the next token\n"
" */\n"
"Token parser_advance(Parser *p);\n"
"\n"
"/* Retrieves the previous token\n"
" *\n"
" * PARAMETERS:\n"
" * 	p: the parser to get the previous token\n"
" *\n"
" * RETURNS:\n"
" * 	the previous token\n"
" */\n"
"Token parser_previous(Parser *p);\n"
"\n"
"/* Retrieves the current token\n"
" *\n"
" * PARAMETERS:\n"
" * 	p: the parser to get the current token\n"
" *\n"
" * RETURNS:\n"
" * 	the current token\n"
" */\n"
"Token parser_current(Parser *p);\n"
"\n"
"/* Checks if a Parser's previously processed Token is of a certain TokenType\n"
" *\n"
" * PARAMETERS:\n"
" * 	p: Parser to check\n"
" * 	tt: TokenType to check for\n"
" *\n"
" * RETURNS:\n"
" * 	If the previously parsed token is of the given type\n"
" */\n"
"bool parser_previous_is(Parser *p, TokenType tt);\n"
"\n"
"/* Peeks the next token without advancing\n"
" *\n"
" * PARAMETERS:\n"
" * 	p: the parser to get the next token\n"
" *\n"
" * RETURNS:\n"
" *	the peeked token\n"
" */\n"
"Token parser_peek(Parser *p);\n"
"\n"
"/* Checks if the next token is of the desired type\n"
" *\n"
" * PARAMETERS:\n"
" * 	p: the parser to check\n"
" * 	tt: the desired token type\n"
" *\n"
" * RETURNS:\n"
" * 	if the next token is of the desired type\n"
" */\n"
"bool parser_check(Parser *p, TokenType tt);\n"
"\n"
"/* Checks and advances if the next token is of the desired type\n"
" *\n"
" * PARAMETERS:\n"
" * 	p: parser to match to\n"
" * 	tt: desired type\n"
" *\n"
" * RETURNS:\n"
" * 	true: if the match was successful\n"
" * 	false: if the match was unsuccessful\n"
" */\n"
"bool parser_match(Parser *p, TokenType tt);\n"
"\n"
"/* Checks and advances if the next token is any of the desired types\n"
" *\n"
" * PARAMETERS:\n"
" * 	p: parser to match to\n"
" * 	tts: an array of expected TokenTypes\n"
" * 	n: length of tts\n"
" *\n"
" * RETURNS:\n"
" * 	true: if the match was successful\n"
" * 	false: if the match was unsuccessful\n"
" */\n"
"bool parser_match_any(Parser *p, TokenType *tts, size_t n);\n"
"\n"
"/* Checks if the parser is at the end of the token stream\n"
" *\n"
" * PARAMETERS:\n"
" * 	p: parser to check\n"
" *\n"
" * RETURNS:\n"
" * 	true: if the parser is at the end\n"
" * 	false: if the parser is not at the end\n"
" */\n"
"bool parser_at_end(Parser *p);\n"
"\n"
"const char *parser_set_error(Parser *p, const char *error);\n"
"\n"
"void parser_reset_error(Parser *p);\n"
"\n"
"bool parser_errored(Parser *p);\n"
"\n"
"AST parser_parse_internal(Parser *p);\n"
"#endif\n";

const char *verbum_parser_file_c_contents = 
"#include \"%s\"\n"
"#include \"%s\"\n"
"#include \"%s\"\n"
"#include \"%s\"\n"
"\n"
"Parser *parser_new(const char *path) {\n"
"	Parser *result = memory_new(1 * sizeof(*result));\n"
"\n"
"	if(result != NULL) {\n"
"		result->l = lexer_new(path);\n"
"		result->previous = (Token) {\n"
"			.type = TokenType_Whitespace,\n"
"			.lexeme = NULL,\n"
"		};\n"
"		result->current = lexer_get_token(result->l);\n"
"		result->peek = lexer_get_token(result->l);\n"
"	}\n"
"\n"
"	return result;\n"
"}\n"

"void parser_delete(Parser *p) {\n"
"	lexer_delete(p->l);\n"
"	memory_delete(p);\n"
"}\n"
"\n"
"AST *parser_parse(Parser *p) {\n"
"	Grammar g1 = parser_parse_internal(p);\n"
"	AST *result = memory_copy(&g1, sizeof(*result));\n"
"\n"
"	return result;\n"
"}\n"
"\n"
"\n"
"Token parser_advance(Parser *p) {\n"
"	if(!parser_at_end(p)) {\n"
"		Token t;\n"
"\n"
"		do {\n"
"			t = lexer_get_token(p->l);\n"
"		} while(t.type == TokenType_Whitespace);\n"
"\n"
"		p->previous = p->current;\n"
"		p->current = p->peek;\n"
"		p->peek = t;\n"
"		p->error = NULL;\n"
"	}\n"
"\n"
"	return parser_current(p);\n"
"}\n"
"\n"
"bool parser_at_end(Parser *p) {\n"
"	return parser_current(p).type == TokenType_EOF;\n"
"}\n"
"\n"
"Token parser_previous(Parser *p) {\n"
"	return p->previous;\n"
"}\n"
"\n"
"Token parser_current(Parser *p) {\n"
"	return p->current;\n"
"}\n"
"\n"
"Token parser_peek(Parser *p) {\n"
"	return p->peek;\n"
"}\n"
"\n"
"bool parser_check(Parser *p, TokenType tt) {\n"
"	return parser_current(p).type == tt;\n"
"}\n"
"\n"
"bool parser_previous_is(Parser *p, TokenType tt) {\n"
"	return parser_previous(p).type == tt;\n"
"}\n"
"\n"
"bool parser_match(Parser *p, TokenType tt) {\n"
"	if(parser_check(p, tt)) {\n"
"		parser_advance(p);\n"
"\n"
"		return true;\n"
"	}\n"
"\n"
"	return false;\n"
"}\n"
"\n"
"bool parser_match_any(Parser *p, TokenType *tts, size_t n) {\n"
"	for(size_t i = 0; i < n; i++) {\n"
"		if(parser_match(p, tts[i])) {\n"
"			return true;\n"
"		}\n"
"	}\n"
"\n"
"	return false;\n"
"}\n"
"\n"
"const char *parser_set_error(Parser *p, const char *error) {\n"
"	p->error = error;\n"
"\n"
"	return error;\n"
"}\n"
"\n"
"void parser_reset_error(Parser *p) {\n"
"	p->error = NULL;\n"
"}\n"
"\n"
"bool parser_errored(Parser *p) {\n"
"	return p->error != NULL;\n"
"}\n"
"\n"
"Grammar parser_parse_internal(Parser *p) {\n"
"	return parser_parse_grammar(p);\n"
"}\n";

const char *verbum_lexer_file_h_contents =
"#ifndef VERBUM_LEXER_H\n"
"#define VERBUM_LEXER_H\n"
"\n"
"#include <stdbool.h>\n"
"#include <stdint.h>\n"
"#include \"%s\"\n" // token
"#include \"%s\"\n" //utf8.h
"#include \"%s\"\n" //utffile8.h
"\n"
"\n"
"/* Opaque declaration */\n"
"typedef struct Lexer Lexer;\n"
"\n"
"/* Constructs a new Lexer\n"
" *\n"
" * PARAMETERS:\n"
" * 	path: path of file to open\n"
" *\n"
" * RETURNS:\n"
" * 	A pointer to a Lexer or NULL on failure\n"
" */\n"
"Lexer *lexer_new(const char *path);\n"
"\n"
"/* Deletes a Lexer\n"
" *\n"
" * PARAMETERS:\n"
" * 	l: a pointer to a lexer\n"
" */\n"
"void lexer_delete(Lexer *l);\n"
"\n"
"/* Retrieves a token\n"
" *\n"
" * PARAMETERS:\n"
" * 	l: a pointer to a Lexer\n"
" *\n"
" * RETURNS:\n"
" * 	The next Token in the stream\n"
" */\n"
"Token lexer_get_token(Lexer *l);\n"
"\n"
"\n"
"\n"
"\n"
"/* Lexer struct\n"
" *\n"
" * MEMBERS:\n"
" * 	f: a pointer to a UTF8File to read from\n"
" * 	pos:\n"
" * 		row: current row in the file\n"
" * 		column: current column in the file\n"
" * 	cc: current character\n"
" */\n"
"typedef struct Lexer {\n"
"	UTF8File *f;\n"
"	struct {\n"
"		uint32_t row;\n"
"		uint32_t col;\n"
"	} pos;\n"
"	utf8_int32_t cc;\n"
"	utf8_int32_t cc (*)"
"} Lexer;\n"
"\n"
"/* Advances a Lexer's position\n"
" *\n"
" * PARAMETERS:\n"
" * 	l: pointer to a Lexer to advance\n"
" * \n"
" * RETURNS:\n"
" * 	The retrieved character from the given Lexer's stream\n"
" */\n"
"utf8_int32_t lexer_advance(Lexer *l);\n"
"\n"
"/* Retrieves the current character of a Lexer\n"
" *\n"
" * PARAMETERS:\n"
" * 	l: a pointer to a Lexer to process\n"
" *\n"
" * RETURNS:\n"
" * 	The current character in the Lexer's stream\n"
" */\n"
"utf8_int32_t lexer_current_character(Lexer *l);\n"
"\n"
"/* Peeks a character in a Lexer's stream\n"
" *\n"
" * PARAMETERS:\n"
" * 	l: a pointer to a Lexer to process\n"
" *\n"
" * RETURNS:\n"
" * 	The next character in the Lexer's stream\n"
" */\n"
"utf8_int32_t lexer_peek_character(Lexer *l);\n"
"\n"
"/* Undos the previous action by a Lexer\n"
" *\n"
" * PARAMETERS:\n"
" * 	l: a pointer to a Lexer to process\n"
" */\n"
"void lexer_undo(Lexer *l);\n"
"\n"
"/* Checks if a Lexer is at the end of its stream\n"
" *\n"
" * PARAMETERS:\n"
" * 	l: a pointer to a Lexer to check\n"
" *\n"
" * RETURNS:\n"
" *	true if the given Lexer is at the end, false otherwise\n"
" */\n"
"bool lexer_at_end(Lexer *l);\n"
"\n"
"/* Reports an error encountered by the Lexer\n"
" *\n"
" * PARAMETERS:\n"
" * 	l: a pointer to a Lexer to propogate the error from\n"
" * 	c: the character that caused the error\n"
" */\n"
"void lexer_report_error(Lexer *l, utf8_int32_t c);\n"
"\n"
"/* Retrieves a token\n"
" *\n"
" * PARAMETERS:\n"
" * 	l: a pointer to a Lexer\n"
" *\n"
" * RETURNS:\n"
" * 	The next Token in the stream\n"
" */\n"
"Token lexer_lex(Lexer *l);\n"
"\n"
"\n"
"#endif\n";
